# .github/workflows/migration-tests.yml
name: Database Migration Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/app/**'
      - '.github/workflows/migration-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/app/**'

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      working-directory: backend/app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run migration tests
      working-directory: backend/app
      run: |
        python run_migration_tests.py
    
    - name: Run pytest
      working-directory: backend/app
      run: |
        pytest test_migrations.py -v
